name: Terraform CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'            
      - '!terraform/.terraform.lock.hcl'  
  pull_request:
    paths:
      - 'terraform/**'
      - '!terraform/.terraform.lock.hcl'

env:
  TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}

jobs:
  terraform:
    name: "Terraform Plan/Apply"
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./terraform  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.4"
          terraform_wrapper: false  
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Format and Validate
        run: |
          terraform fmt -check -recursive  
          terraform validate               

      - name: Terraform Plan
        run: terraform plan -no-color -input=false
        if: github.event_name == 'pull_request'  # Only plan for PRs

      # - name: Terraform Apply
      #   run: terraform apply -input=false -auto-approve
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
